name: Prepare CI cache

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  prepare-npm-cache:
    name: Prepare npm cache for ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: lts/*
          cache: npm
      - name: Validate cache
        run: npm ci
